"""init

Revision ID: f1169b7d0f59
Revises: 
Create Date: 2026-04-15 10:54:14.736784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1169b7d0f59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_word_id'), table_name='vocabulary')
    op.drop_table('vocabulary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('word_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('english_word', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('part_of_speech', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phonetic_transcription', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_storage_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telegram_file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('word_id', name=op.f('vocabulary_pkey'))
    )
    op.create_index(op.f('ix_vocabulary_word_id'), 'vocabulary', ['word_id'], unique=False)
    # ### end Alembic commands ###
