"""init

Revision ID: f206ab885139
Revises: 
Create Date: 2026-04-26 12:42:33.049219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f206ab885139'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('english_word', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('phonetic_transcription', sa.String(), nullable=True),
    sa.Column('raw_storage_url', sa.String(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary')
    # ### end Alembic commands ###
